### ISSUE TITLE
arcage原稿

### ISSUE THREAD

**Issue by arcage** [crystal-jp/techbookfest3#2]
arcageブランチを切って初稿を上げました。

お気付きの点などありましたらご指摘いただけるとありがたいです。

https://github.com/crystal-jp/techbookfest3/tree/arcage

**Comment by makenowjust** [comment]
@arcage 早めの原稿ありがとうございます。自分は今ちょっと忙しくて時間が取れないので、一週間後くらいに確認します。

**Comment by sdogruyol** [comment]
ありがとうございます！

**Comment by makenowjust** [comment]
@sdogruyol セドさんも何か書きますか？

**Comment by sdogruyol** [comment]
まだ早いですけど僕はクリスタルの本を書いてますw。

**Comment by arcage** [comment]
@MakeNowJust 
自分でも校正していくつもりですが，よろしくお願いします。

@sdogruyol 
本を書かれてるんですか，凄いですね。
いつか日本語訳が出るのかな? 😄

**Comment by makenowjust** [comment]
@sdogruyol わりと真面目な話、いつかセドさんにも記事を書いてもらいたいなと思ってます。今回はさすがに厳しいと思うのですけど、検討してもらえたら嬉しいです。

**Comment by sdogruyol** [comment]
@arcageさん。ありがとう。日本語訳が僕も欲しいですでもそれはまだクリスタル１。０の後ですね。

@MakeNowJust さん。いつか僕も日本語で記事とか書きたいです。僕の日本語はそんなに強いところじゃないですから貴方たちのサーポートは大事です。

**Comment by at-grandpa** [comment]
@sdogruyol さん、本を書かれているのですね。とても楽しみ！

**Comment by at-grandpa** [comment]
@arcage さん、こちらまだ読めていませんが、指摘等し易いようにPR出すのはどうでしょうか？

コメント付けやすくなると思います。

**Comment by arcage** [comment]
@at-grandpa 
そうですね，ありがとうございます。
現在，自分で読み返すたびにアラを見つけては潰しているような状態ですので，
その辺りをある程度Fixさせて，この週末か週明け早々にはPRを出せるようにしたいと思います。

**Comment by arcage** [comment]
PRを出しましたのでこちらはcloseします。
